config/routes.rb
Rails.application.routes.draw do

  match '/push/history',:controller=>'iopushes',:action=>'generateHistory',via:[:get]
  match '/push/update',:controller=>'iopushes',:action=>'updateToken',via:[:post]
  resources :iopushes
  
  resources :plastics

  resources :likes

  resources :notifications

  resources :pushes

  resources :adserviceusers

  match '/adservices/getAdByPlace',:controller=>'adservices',:action=>'getAdByPlace',via:[:get,:post]
  resources :adservices

  match '/dashbuttons/attachDash',:controller=>'dashbuttons',:action=>'attachDash',via:[:get,:post]
  match '/dashbuttons/pushDash',:controller=>'dashbuttons',:action=>'pushDash',via:[:get,:post]
  resources :dashbuttons

  match '/servicios/beacon',:controller=>'servicios',:action=>'showServicesByLocation',via:[:get,:post]
  resources :servicios

  match '/mastercard/yomero',:controller=>'mastercards',:action=>'yomero',via:[:get,:post]
  match '/mastercard/fromBeacon',:controller=>'mastercards',:action=>'fromBeacon',via:[:get,:post]
  match '/mastercard/closeTransaction',:controller=>'mastercards',:action=>'closeTransaction',via:[:get,:post]
  resources :mastercards

  resources :publicidads

  get 'analytics/show'

  get 'analytics/logs'

  get 'analytics/chart'

  match '/analytics/destroy',:controller=>'analytics',:action=>'destroy',via: [:post]

  match '/pagos/calculatePrice',:controller=>'pagos',:action=>'calculatePrice',via: [:get, :post]
  match '/pagos/incomingFromGateway',:controller=>'pagos',:action=>'incomingFromGateway',via: [:get, :post]

  match '/pagos/fake',:controller=>'pagos',:action=>'fakeAuthorize',via: [:get]
  resources :pagos

  resources :preciohoras
  resources :precios

  match '/campaigns/getRankedCampaigns',:controller=>'campaigns',:action=>'getRankedCampaigns',via: [:get,:post]
  match '/campaigns/buy',:controller=>'campaigns',:action=>'commitToBuy',via: [:post]
  resources :campaigns

  resources :geofencings

  
  resources :places

  resources :welcomes

  resources :mail_templates

  match '/entrances/getAllUsersAsJson',:controller=>'entrances',:action=>'getAllUsersAsJson',via: [:get, :post]
  match '/entrances/getUserPromos',:controller=>'entrances',:action=>'getUserPromos',via: [:get, :post]
  match '/entrances/logout',:controller=>'entrances',:action=>'logout',via: [:get, :post]
  match '/entrances/createToken',:controller=>'entrances',:action=>'createToken',via: [:get,:post]
  match '/entrances/getUserDetails',:controller=>'entrances',:action=>'getUserDetails',via: [:get,:post]
  match '/entrances/setUserDetails',:controller=>'entrances',:action=>'setUserDetails',via: [:get,:post]
  match '/entrances/history',:controller=>'entrances',:action=>'history',via: [:get,:post]
  match '/reservations/getplaces',:controller=>'entrances',:action=>'getParkingLot',via: [:post]

  resources :entrances
  get '/login', to: 'entrances#index'
  get '/register', to: 'entrances#index'
  get '/forget', to: 'entrances#index'

  match '/entrances/createAccount',:controller=>'entrances',:action=>'createAccount',via: [:get, :post]
  match '/entrances/resetAccount',:controller=>'entrances',:action=>'resetAccount',via: [:get, :post]
  get '/entrances/confirmAccount/:id',:controller=>'entrances',:action=>'confirmAccount'
  match '/entrances/loginAccount',:controller=>'entrances',:action=>'loginAccount',via: [:get, :post]

  match '/beacons/getCloudBeacons',:controller=>'beacons',:action=>'getCloudBeacons',via: [:get,:post]
  match '/beacons/interchangeBeaconLocation',:controller=>'beacons',:action=>'interchangeBeaconLocation',via: [:get,:post]
  match '/beacons/exchangeReward',:controller=>'beacons',:action=>'exchangeReward',via: [:get,:post]
  match '/beacons/isRewardAvailable',:controller=>'beacons',:action=>'isRewardAvailable',via: [:get,:post]
  match '/beacons/getOliiPrice',:controller=>'beacons',:action=>'getOliiPrice',via: [:get,:post]
  match '/beacons/getPaidOlii',:controller=>'beacons',:action=>'getPaidOlii',via: [:get,:post]
  resources :beacons

end

app/models/mail_template.rb
class MailTemplate < ActiveRecord::Base
	
end

app/controllers/mail_templates_controller.rb
class MailTemplatesController < ApplicationController
  before_action :set_mail_template, only: [:show, :edit, :update, :destroy]

  # GET /mail_templates
  # GET /mail_templates.json
  def index
    supuestoUsuario=Entrance.find_by_id(session[:cuser])
    if supuestoUsuario==nil
      redirect_to "/login"
      return
    end
    if supuestoUsuario.superlevel<1000
      redirect_to "/login"
      return
    end
    
    @mail_templates = MailTemplate.all
  end

  # GET /mail_templates/1
  # GET /mail_templates/1.json
  def show
    supuestoUsuario=Entrance.find_by_id(session[:cuser])
    if supuestoUsuario==nil
      redirect_to "/login"
      return
    end
    if supuestoUsuario.superlevel<1000
      redirect_to "/login"
      return
    end
  end

  # GET /mail_templates/new
  def new
    supuestoUsuario=Entrance.find_by_id(session[:cuser])
    if supuestoUsuario==nil
      redirect_to "/login"
      return
    end
    if supuestoUsuario.superlevel<1000
      redirect_to "/login"
      return
    end
    @mail_template = MailTemplate.new
  end

  # GET /mail_templates/1/edit
  def edit
    supuestoUsuario=Entrance.find_by_id(session[:cuser])
    if supuestoUsuario==nil
      redirect_to "/login"
      return
    end
    if supuestoUsuario.superlevel<1000
      redirect_to "/login"
      return
    end
  end

  # POST /mail_templates
  # POST /mail_templates.json
  def create
    supuestoUsuario=Entrance.find_by_id(session[:cuser])
    if supuestoUsuario==nil
      redirect_to "/login"
      return
    end
    if supuestoUsuario.superlevel<1000
      redirect_to "/login"
      return
    end
    @mail_template = MailTemplate.new(mail_template_params)

    respond_to do |format|
      if @mail_template.save
        format.html { redirect_to mail_templates_url, notice: 'Mail template was successfully created.' }
        format.json { render :show, status: :created, location: @mail_template }
      else
        format.html { render :new }
        format.json { render json: @mail_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mail_templates/1
  # PATCH/PUT /mail_templates/1.json
  def update
    supuestoUsuario=Entrance.find_by_id(session[:cuser])
    if supuestoUsuario==nil
      redirect_to "/login"
      return
    end
    if supuestoUsuario.superlevel<1000
      redirect_to "/login"
      return
    end
    respond_to do |format|
      if @mail_template.update(mail_template_params)
        format.html { redirect_to "/mail_templates", notice: 'Mail template was successfully updated.' }
        format.json { render :show, status: :ok, location: @mail_template }
      else
        format.html { render :edit }
        format.json { render json: @mail_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mail_templates/1
  # DELETE /mail_templates/1.json
  def destroy
    supuestoUsuario=Entrance.find_by_id(session[:cuser])
    if supuestoUsuario==nil
      redirect_to "/login"
      return
    end
    if supuestoUsuario.superlevel<1000
      redirect_to "/login"
      return
    end
    @mail_template.destroy
    respond_to do |format|
      format.html { redirect_to mail_templates_url, notice: 'Mail template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mail_template
      @mail_template = MailTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mail_template_params
      params.require(:mail_template).permit(:template, :mensaje, :titulo,:evento)
    end
end

app/helpers/mail_templates_helper.rb
module MailTemplatesHelper
end

app/views/mail_templates/_form.html.erb
<%= form_for(@mail_template) do |f| %>
  <% if @mail_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mail_template.errors.count, "error") %> prohibited this mail_template from being saved:</h2>

      <ul>
      <% @mail_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :template %><br>
    <%= f.text_area :template %>
  </div>
  <div class="field">
    <%= f.label :mensaje %><br>
    <%= f.text_field :mensaje %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :evento %><br>
    <%= f.text_field :evento %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mail_templates/edit.html.erb
<%= render "shared/top_menu" %>
<div id="base">
<%= render "shared/left_menu" %>

<div id="content">

        <!-- START BLANK SECTION -->
        <section>
          <ol class="breadcrumb">
            <li><a href="../../html/.html">home</a></li>
            <li class="active"><%= t(:users) %></li>
          </ol>
          <div class="section-header">
            <h3 class="text-standard"><i class="fa fa-fw fa-arrow-circle-right text-gray-light"></i> Blank page <small>Handy when you need to create a new page</small></h3>
          </div>
          <div class="section-body">
          <div class="row">
              <div class="col-lg-12">
                <div class="box">
                  <div class="box-head">
                    <header><h4 class="text-light"><%= t(:listing) %> <strong><%= t(:users) %></strong></h4></header>
                  </div>
                  <div class="box-body">
                    <%= render 'form' %>

<%= link_to 'Show', @mail_template %> |
<%= link_to 'Back', mail_templates_path %>
                  </div><!--end .box-body -->
                </div><!--end .box -->
              </div><!--end .col-lg-12 -->
            </div>
          

  
    
 

<br>


          </div><!--end .section-body -->
        </section>
        <!-- START BLANK SECTION -->
      </div><!--end #content-->
      <!-- END CONTENT -->

    </div><!--end #base-->

app/views/mail_templates/index.html.erb
<%= render "shared/top_menu" %>
<div id="base">
<%= render "shared/left_menu" %>

<div id="content">

        <!-- START BLANK SECTION -->
        <section>
          <ol class="breadcrumb">
            <li><a href="../../html/.html">home</a></li>
            <li class="active">Template</li>
          </ol>
          <div class="section-header">
            <h3 class="text-standard"><i class="fa fa-fw fa-arrow-circle-right text-gray-light"></i> Blank page <small>Handy when you need to create a new page</small></h3>
          </div>
          <div class="section-body">
          <div class="row">
              <div class="col-lg-12">
                <div class="box">
                  <div class="box-head">
                    <header><h4 class="text-light"><%= t(:listing) %> <strong> Templates</strong></h4></header>
                    <%= link_to 'New Mail template', new_mail_template_path %>
                  </div>
                  <div class="box-body">
                    <table class="table table-hover">
                      
  <thead>
    <tr>
      
      <th>Mensaje</th>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mail_templates.each do |mail_template| %>
      <tr>
        
        <td><%= mail_template.mensaje %></td>
        <td><%= mail_template.titulo %></td>
        <td><%= link_to 'Show', mail_template %></td>
        <td><%= link_to 'Edit', edit_mail_template_path(mail_template) %></td>
        <td><%= link_to 'Destroy', mail_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>





                  </div><!--end .box-body -->
                </div><!--end .box -->
              </div><!--end .col-lg-12 -->
            </div>
          

  
    
 

<br>


          </div><!--end .section-body -->
        </section>
        <!-- START BLANK SECTION -->
      </div><!--end #content-->
      <!-- END CONTENT -->

    </div><!--end #base-->

app/views/mail_templates/new.html.erb
<h1>New mail_template</h1>

<%= render 'form' %>

<%= link_to 'Back', mail_templates_path %>

app/views/mail_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Template:</strong>
  <%= @mail_template.template %>
</p>

<p>
  <strong>Mensaje:</strong>
  <%= @mail_template.mensaje %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @mail_template.titulo %>
</p>

<%= link_to 'Edit', edit_mail_template_path(@mail_template) %> |
<%= link_to 'Back', mail_templates_path %>