config/routes.rb
Rails.application.routes.draw do

  match '/push/history',:controller=>'iopushes',:action=>'generateHistory',via:[:get]
  match '/push/update',:controller=>'iopushes',:action=>'updateToken',via:[:post]
  resources :iopushes
  
  resources :plastics

  resources :likes

  resources :notifications

  resources :pushes

  resources :adserviceusers

  match '/adservices/getAdByPlace',:controller=>'adservices',:action=>'getAdByPlace',via:[:get,:post]
  resources :adservices

  match '/dashbuttons/attachDash',:controller=>'dashbuttons',:action=>'attachDash',via:[:get,:post]
  match '/dashbuttons/pushDash',:controller=>'dashbuttons',:action=>'pushDash',via:[:get,:post]
  resources :dashbuttons

  match '/servicios/beacon',:controller=>'servicios',:action=>'showServicesByLocation',via:[:get,:post]
  resources :servicios

  match '/mastercard/yomero',:controller=>'mastercards',:action=>'yomero',via:[:get,:post]
  match '/mastercard/fromBeacon',:controller=>'mastercards',:action=>'fromBeacon',via:[:get,:post]
  match '/mastercard/closeTransaction',:controller=>'mastercards',:action=>'closeTransaction',via:[:get,:post]
  resources :mastercards

  resources :publicidads

  get 'analytics/show'

  get 'analytics/logs'

  get 'analytics/chart'

  match '/analytics/destroy',:controller=>'analytics',:action=>'destroy',via: [:post]

  match '/pagos/calculatePrice',:controller=>'pagos',:action=>'calculatePrice',via: [:get, :post]
  match '/pagos/incomingFromGateway',:controller=>'pagos',:action=>'incomingFromGateway',via: [:get, :post]

  match '/pagos/fake',:controller=>'pagos',:action=>'fakeAuthorize',via: [:get]
  resources :pagos

  resources :preciohoras
  resources :precios

  match '/campaigns/getRankedCampaigns',:controller=>'campaigns',:action=>'getRankedCampaigns',via: [:get,:post]
  match '/campaigns/buy',:controller=>'campaigns',:action=>'commitToBuy',via: [:post]
  resources :campaigns

  resources :geofencings

  
  resources :places

  resources :welcomes

  resources :mail_templates

  match '/entrances/getAllUsersAsJson',:controller=>'entrances',:action=>'getAllUsersAsJson',via: [:get, :post]
  match '/entrances/getUserPromos',:controller=>'entrances',:action=>'getUserPromos',via: [:get, :post]
  match '/entrances/logout',:controller=>'entrances',:action=>'logout',via: [:get, :post]
  match '/entrances/createToken',:controller=>'entrances',:action=>'createToken',via: [:get,:post]
  match '/entrances/getUserDetails',:controller=>'entrances',:action=>'getUserDetails',via: [:get,:post]
  match '/entrances/setUserDetails',:controller=>'entrances',:action=>'setUserDetails',via: [:get,:post]
  match '/entrances/history',:controller=>'entrances',:action=>'history',via: [:get,:post]
  match '/reservations/getplaces',:controller=>'entrances',:action=>'getParkingLot',via: [:post]

  resources :entrances
  get '/login', to: 'entrances#index'
  get '/register', to: 'entrances#index'
  get '/forget', to: 'entrances#index'

  match '/entrances/createAccount',:controller=>'entrances',:action=>'createAccount',via: [:get, :post]
  match '/entrances/resetAccount',:controller=>'entrances',:action=>'resetAccount',via: [:get, :post]
  get '/entrances/confirmAccount/:id',:controller=>'entrances',:action=>'confirmAccount'
  match '/entrances/loginAccount',:controller=>'entrances',:action=>'loginAccount',via: [:get, :post]

  match '/beacons/getCloudBeacons',:controller=>'beacons',:action=>'getCloudBeacons',via: [:get,:post]
  match '/beacons/interchangeBeaconLocation',:controller=>'beacons',:action=>'interchangeBeaconLocation',via: [:get,:post]
  match '/beacons/exchangeReward',:controller=>'beacons',:action=>'exchangeReward',via: [:get,:post]
  match '/beacons/isRewardAvailable',:controller=>'beacons',:action=>'isRewardAvailable',via: [:get,:post]
  match '/beacons/getOliiPrice',:controller=>'beacons',:action=>'getOliiPrice',via: [:get,:post]
  match '/beacons/getPaidOlii',:controller=>'beacons',:action=>'getPaidOlii',via: [:get,:post]
  resources :beacons

end

app/models/adservice.rb
class Adservice < ActiveRecord::Base
end

app/models/beacon.rb
class Beacon < ActiveRecord::Base
end

app/models/beaconlog.rb
class Beaconlog < ActiveRecord::Base
	def hour
	  self.created_at.to_date.strftime('%H')
	end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
end

app/models/dashbutton.rb
class Dashbutton < ActiveRecord::Base
end

app/models/entrance.rb
class Entrance < ActiveRecord::Base
end

app/models/geofencing.rb
class Geofencing < ActiveRecord::Base
end

app/models/iopush.rb
class Iopush < ActiveRecord::Base
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/mastercard.rb
class Mastercard < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/pago.rb
class Pago < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/plastic.rb
class Plastic < ActiveRecord::Base
end

app/models/precio.rb
class Precio < ActiveRecord::Base
end

app/models/preciohora.rb
class Preciohora < ActiveRecord::Base
end

app/models/publicidad.rb
class Publicidad < ActiveRecord::Base
end

app/models/push.rb
class Push < ActiveRecord::Base
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/notifications_controller.rb
require 'pusher'
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        Pusher.url = "https://aa50b9b2b70a85ae6cb8:5bba1696c5f58caaba98@api.pusherapp.com/apps/172196"
        Pusher.trigger(@notification.channel, @notification.screen, {
          message: @notification.dato
        })
        format.html { redirect_to "/notifications", notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to "/notifications", notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:channel, :screen, :dato, :users)
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= simple_form_for @notification,:html => { role: 'form' } do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
Channels: incuvaSite,incuvaApp
<br>
Screen: dashboard
  <div class="form-group">
    <%= f.label :channel %><br>
    <%= f.text_field :channel, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :screen %><br>
    <%= f.text_field :screen,class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :dato %><br>
    <%= f.text_field :dato, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :users %><br>
    <%= f.text_field :users, class: 'form-control'  %>
  </div>
  <div class="actions">
    <%= f.submit class:'btn btn-danger' %>

  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<%= render "shared/top_menu" %>
<div id="base">
<%= render "shared/left_menu" %>

<div id="content">

        <!-- START BLANK SECTION -->
        <section>
          <ol class="breadcrumb">
            <li><a href="../../html/.html">home</a></li>
            <li class="active">Notifications</li>
          </ol>
          <div class="section-header">
            <h3 class="text-standard"><i class="fa fa-fw fa-arrow-circle-right text-gray-light"></i> Notifications <small></small></h3>
          </div>
          <div class="section-body">
            

            <table class="table">
  <thead>
    <tr>
      <th>Channel</th>
      <th>Screen</th>
      <th>Dato</th>
      <th>Users</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= notification.channel %></td>
        <td><%= notification.screen %></td>
        <td><%= notification.dato %></td>
        <td><%= notification.users %></td>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<a href="/notifications/new" class="btn btn-default">New notification</a>

<% link_to 'New Notification', new_notification_path %>

          </div><!--end .section-body -->
        </section>
        <!-- START BLANK SECTION -->
      </div><!--end #content-->
      <!-- END CONTENT -->

    </div><!--end #base-->

app/views/notifications/new.html.erb
<%= render "shared/top_menu" %>
<div id="base">
<%= render "shared/left_menu" %>

<div id="content">

        <!-- START BLANK SECTION -->
        <section>
          <ol class="breadcrumb">
            <li><a href="../../html/.html">home</a></li>
            <li class="active">New notification</li>
          </ol>
          <div class="section-header">
            <h3 class="text-standard"><i class="fa fa-fw fa-arrow-circle-right text-gray-light"></i> Bienvenido <small></small></h3>
          </div>
          <div class="section-body">
          	<%= render 'form' %>

<%= link_to 'Back', notifications_path %>
          </div><!--end .section-body -->
        </section>
        <!-- START BLANK SECTION -->
      </div><!--end #content-->
      <!-- END CONTENT -->

    </div><!--end #base-->

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Channel:</strong>
  <%= @notification.channel %>
</p>

<p>
  <strong>Screen:</strong>
  <%= @notification.screen %>
</p>

<p>
  <strong>Dato:</strong>
  <%= @notification.dato %>
</p>

<p>
  <strong>Users:</strong>
  <%= @notification.users %>
</p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>