config/routes.rb
Rails.application.routes.draw do

  match '/push/history',:controller=>'iopushes',:action=>'generateHistory',via:[:get]
  match '/push/update',:controller=>'iopushes',:action=>'updateToken',via:[:post]
  resources :iopushes
  
  resources :plastics

  resources :likes

  resources :notifications

  resources :pushes

  resources :adserviceusers

  match '/adservices/getAdByPlace',:controller=>'adservices',:action=>'getAdByPlace',via:[:get,:post]
  resources :adservices

  match '/dashbuttons/attachDash',:controller=>'dashbuttons',:action=>'attachDash',via:[:get,:post]
  match '/dashbuttons/pushDash',:controller=>'dashbuttons',:action=>'pushDash',via:[:get,:post]
  resources :dashbuttons

  match '/servicios/beacon',:controller=>'servicios',:action=>'showServicesByLocation',via:[:get,:post]
  resources :servicios

  match '/mastercard/yomero',:controller=>'mastercards',:action=>'yomero',via:[:get,:post]
  match '/mastercard/fromBeacon',:controller=>'mastercards',:action=>'fromBeacon',via:[:get,:post]
  match '/mastercard/closeTransaction',:controller=>'mastercards',:action=>'closeTransaction',via:[:get,:post]
  resources :mastercards

  resources :publicidads

  get 'analytics/show'

  get 'analytics/logs'

  get 'analytics/chart'

  match '/analytics/destroy',:controller=>'analytics',:action=>'destroy',via: [:post]

  match '/pagos/calculatePrice',:controller=>'pagos',:action=>'calculatePrice',via: [:get, :post]
  match '/pagos/incomingFromGateway',:controller=>'pagos',:action=>'incomingFromGateway',via: [:get, :post]

  match '/pagos/fake',:controller=>'pagos',:action=>'fakeAuthorize',via: [:get]
  resources :pagos

  resources :preciohoras
  resources :precios

  match '/campaigns/getRankedCampaigns',:controller=>'campaigns',:action=>'getRankedCampaigns',via: [:get,:post]
  match '/campaigns/buy',:controller=>'campaigns',:action=>'commitToBuy',via: [:post]
  resources :campaigns

  resources :geofencings

  
  resources :places

  resources :welcomes

  resources :mail_templates

  match '/entrances/getAllUsersAsJson',:controller=>'entrances',:action=>'getAllUsersAsJson',via: [:get, :post]
  match '/entrances/getUserPromos',:controller=>'entrances',:action=>'getUserPromos',via: [:get, :post]
  match '/entrances/logout',:controller=>'entrances',:action=>'logout',via: [:get, :post]
  match '/entrances/createToken',:controller=>'entrances',:action=>'createToken',via: [:get,:post]
  match '/entrances/getUserDetails',:controller=>'entrances',:action=>'getUserDetails',via: [:get,:post]
  match '/entrances/setUserDetails',:controller=>'entrances',:action=>'setUserDetails',via: [:get,:post]
  match '/entrances/history',:controller=>'entrances',:action=>'history',via: [:get,:post]
  match '/reservations/getplaces',:controller=>'entrances',:action=>'getParkingLot',via: [:post]

  resources :entrances
  get '/login', to: 'entrances#index'
  get '/register', to: 'entrances#index'
  get '/forget', to: 'entrances#index'

  match '/entrances/createAccount',:controller=>'entrances',:action=>'createAccount',via: [:get, :post]
  match '/entrances/resetAccount',:controller=>'entrances',:action=>'resetAccount',via: [:get, :post]
  get '/entrances/confirmAccount/:id',:controller=>'entrances',:action=>'confirmAccount'
  match '/entrances/loginAccount',:controller=>'entrances',:action=>'loginAccount',via: [:get, :post]

  match '/beacons/getCloudBeacons',:controller=>'beacons',:action=>'getCloudBeacons',via: [:get,:post]
  match '/beacons/interchangeBeaconLocation',:controller=>'beacons',:action=>'interchangeBeaconLocation',via: [:get,:post]
  match '/beacons/exchangeReward',:controller=>'beacons',:action=>'exchangeReward',via: [:get,:post]
  match '/beacons/isRewardAvailable',:controller=>'beacons',:action=>'isRewardAvailable',via: [:get,:post]
  match '/beacons/getOliiPrice',:controller=>'beacons',:action=>'getOliiPrice',via: [:get,:post]
  match '/beacons/getPaidOlii',:controller=>'beacons',:action=>'getPaidOlii',via: [:get,:post]
  resources :beacons

end

app/models/adservice.rb
class Adservice < ActiveRecord::Base
end

app/controllers/adservices_controller.rb
class AdservicesController < ApplicationController
  before_action :set_adservice, only: [:show, :edit, :update, :destroy]

  # GET /adservices
  # GET /adservices.json
  def index
    @adservices = Adservice.all
  end

  def getAdByPlace
    hashResponse=Hash.new
    tiempo=Time.now - 6
    imagenes=["http://avantumcomunicacion.com/wp-content/uploads/2014/08/Coca-Cola3.jpg","http://paseoaltozano.com/wp-content/uploads/2015/09/telcel.jpg","http://dbakevlar.com/wp-content/uploads/2015/03/Team-Oracle.jpg","http://keyassets.timeincuk.net/inspirewp/live/wp-content/uploads/sites/21/2013/08/Oracle_AC45.png","http://beamk-dimole.rhcloud.com/assets/child.mp4"]
    # Movie.where(['release > ?', DateTime.now])
    cuenta=Adserviceuser.where(['created_at > ?', tiempo]).where(:beacon=>params["adNumber"])
    
    if cuenta.length>0
      hashResponse["media_url"]=imagenes[rand(0..imagenes.length-1)]
      if hashResponse["media_url"].index(".jpg")!=nil or hashResponse["media_url"].index(".png")!=nil
        hashResponse["media_type"]="image"  
      else
        hashResponse["media_type"]="video"
      end
    else
      hashResponse["media_url"]="none"
      hashResponse["media_type"]="none"
    end
    # puts params["adNumber"]
    # if params["adNumber"]==1 or params["adNumber"]=="1"
    #   hashResponse["media_url"]="http://beamk-dimole.rhcloud.com/assets/img/img1.jpg"
    #   hashResponse["media_type"]="none1"
    # elsif params["adNumber"]==2 or params["adNumber"]=="2"
    #   hashResponse["media_url"]="http://beamk-dimole.rhcloud.com/assets/testing.mp4"
    #   hashResponse["media_type"]="none2"
    # end
      
    respond_to do |format|        
        format.json { render json: hashResponse }
    end
  end

  # GET /adservices/1
  # GET /adservices/1.json
  def show
  end

  # GET /adservices/new
  def new
    @adservice = Adservice.new
  end

  # GET /adservices/1/edit
  def edit
  end

  # POST /adservices
  # POST /adservices.json
  def create
    @adservice = Adservice.new(adservice_params)

    respond_to do |format|
      if @adservice.save
        format.html { redirect_to @adservice, notice: 'Adservice was successfully created.' }
        format.json { render :show, status: :created, location: @adservice }
      else
        format.html { render :new }
        format.json { render json: @adservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adservices/1
  # PATCH/PUT /adservices/1.json
  def update
    respond_to do |format|
      if @adservice.update(adservice_params)
        format.html { redirect_to @adservice, notice: 'Adservice was successfully updated.' }
        format.json { render :show, status: :ok, location: @adservice }
      else
        format.html { render :edit }
        format.json { render json: @adservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adservices/1
  # DELETE /adservices/1.json
  def destroy
    @adservice.destroy
    respond_to do |format|
      format.html { redirect_to adservices_url, notice: 'Adservice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adservice
      @adservice = Adservice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adservice_params
      params.require(:adservice).permit(:name, :age_from, :age_to, :content_type, :url_content, :genre)
    end
end

app/helpers/adservices_helper.rb
module AdservicesHelper
end

app/views/adservices/_form.html.erb
<%= form_for(@adservice) do |f| %>
  <% if @adservice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adservice.errors.count, "error") %> prohibited this adservice from being saved:</h2>

      <ul>
      <% @adservice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age_from %><br>
    <%= f.number_field :age_from %>
  </div>
  <div class="field">
    <%= f.label :age_to %><br>
    <%= f.number_field :age_to %>
  </div>
  <div class="field">
    <%= f.label :content_type %><br>
    <%= f.text_field :content_type %>
  </div>
  <div class="field">
    <%= f.label :url_content %><br>
    <%= f.text_field :url_content %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adservices/edit.html.erb
<h1>Editing adservice</h1>

<%= render 'form' %>

<%= link_to 'Show', @adservice %> |
<%= link_to 'Back', adservices_path %>

app/views/adservices/index.html.erb
<h1>Listing adservices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age from</th>
      <th>Age to</th>
      <th>Content type</th>
      <th>Url content</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adservices.each do |adservice| %>
      <tr>
        <td><%= adservice.name %></td>
        <td><%= adservice.age_from %></td>
        <td><%= adservice.age_to %></td>
        <td><%= adservice.content_type %></td>
        <td><%= adservice.url_content %></td>
        <td><%= adservice.genre %></td>
        <td><%= link_to 'Show', adservice %></td>
        <td><%= link_to 'Edit', edit_adservice_path(adservice) %></td>
        <td><%= link_to 'Destroy', adservice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adservice', new_adservice_path %>

app/views/adservices/new.html.erb
<h1>New adservice</h1>

<%= render 'form' %>

<%= link_to 'Back', adservices_path %>

app/views/adservices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @adservice.name %>
</p>

<p>
  <strong>Age from:</strong>
  <%= @adservice.age_from %>
</p>

<p>
  <strong>Age to:</strong>
  <%= @adservice.age_to %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @adservice.content_type %>
</p>

<p>
  <strong>Url content:</strong>
  <%= @adservice.url_content %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @adservice.genre %>
</p>

<%= link_to 'Edit', edit_adservice_path(@adservice) %> |
<%= link_to 'Back', adservices_path %>