config/routes.rb
Rails.application.routes.draw do

  match '/push/history',:controller=>'iopushes',:action=>'generateHistory',via:[:get]
  match '/push/update',:controller=>'iopushes',:action=>'updateToken',via:[:post]
  resources :iopushes
  
  resources :plastics

  resources :likes

  resources :notifications

  resources :pushes

  resources :adserviceusers

  match '/adservices/getAdByPlace',:controller=>'adservices',:action=>'getAdByPlace',via:[:get,:post]
  resources :adservices

  match '/dashbuttons/attachDash',:controller=>'dashbuttons',:action=>'attachDash',via:[:get,:post]
  match '/dashbuttons/pushDash',:controller=>'dashbuttons',:action=>'pushDash',via:[:get,:post]
  resources :dashbuttons

  match '/servicios/beacon',:controller=>'servicios',:action=>'showServicesByLocation',via:[:get,:post]
  resources :servicios

  match '/mastercard/yomero',:controller=>'mastercards',:action=>'yomero',via:[:get,:post]
  match '/mastercard/fromBeacon',:controller=>'mastercards',:action=>'fromBeacon',via:[:get,:post]
  match '/mastercard/closeTransaction',:controller=>'mastercards',:action=>'closeTransaction',via:[:get,:post]
  resources :mastercards

  resources :publicidads

  get 'analytics/show'

  get 'analytics/logs'

  get 'analytics/chart'

  match '/analytics/destroy',:controller=>'analytics',:action=>'destroy',via: [:post]

  match '/pagos/calculatePrice',:controller=>'pagos',:action=>'calculatePrice',via: [:get, :post]
  match '/pagos/incomingFromGateway',:controller=>'pagos',:action=>'incomingFromGateway',via: [:get, :post]

  match '/pagos/fake',:controller=>'pagos',:action=>'fakeAuthorize',via: [:get]
  resources :pagos

  resources :preciohoras
  resources :precios

  match '/campaigns/getRankedCampaigns',:controller=>'campaigns',:action=>'getRankedCampaigns',via: [:get,:post]
  match '/campaigns/buy',:controller=>'campaigns',:action=>'commitToBuy',via: [:post]
  resources :campaigns

  resources :geofencings

  
  resources :places

  resources :welcomes

  resources :mail_templates

  match '/entrances/getAllUsersAsJson',:controller=>'entrances',:action=>'getAllUsersAsJson',via: [:get, :post]
  match '/entrances/getUserPromos',:controller=>'entrances',:action=>'getUserPromos',via: [:get, :post]
  match '/entrances/logout',:controller=>'entrances',:action=>'logout',via: [:get, :post]
  match '/entrances/createToken',:controller=>'entrances',:action=>'createToken',via: [:get,:post]
  match '/entrances/getUserDetails',:controller=>'entrances',:action=>'getUserDetails',via: [:get,:post]
  match '/entrances/setUserDetails',:controller=>'entrances',:action=>'setUserDetails',via: [:get,:post]
  match '/entrances/history',:controller=>'entrances',:action=>'history',via: [:get,:post]
  match '/reservations/getplaces',:controller=>'entrances',:action=>'getParkingLot',via: [:post]

  resources :entrances
  get '/login', to: 'entrances#index'
  get '/register', to: 'entrances#index'
  get '/forget', to: 'entrances#index'

  match '/entrances/createAccount',:controller=>'entrances',:action=>'createAccount',via: [:get, :post]
  match '/entrances/resetAccount',:controller=>'entrances',:action=>'resetAccount',via: [:get, :post]
  get '/entrances/confirmAccount/:id',:controller=>'entrances',:action=>'confirmAccount'
  match '/entrances/loginAccount',:controller=>'entrances',:action=>'loginAccount',via: [:get, :post]

  match '/beacons/getCloudBeacons',:controller=>'beacons',:action=>'getCloudBeacons',via: [:get,:post]
  match '/beacons/interchangeBeaconLocation',:controller=>'beacons',:action=>'interchangeBeaconLocation',via: [:get,:post]
  match '/beacons/exchangeReward',:controller=>'beacons',:action=>'exchangeReward',via: [:get,:post]
  match '/beacons/isRewardAvailable',:controller=>'beacons',:action=>'isRewardAvailable',via: [:get,:post]
  match '/beacons/getOliiPrice',:controller=>'beacons',:action=>'getOliiPrice',via: [:get,:post]
  match '/beacons/getPaidOlii',:controller=>'beacons',:action=>'getPaidOlii',via: [:get,:post]
  resources :beacons

end

app/models/adservice.rb
class Adservice < ActiveRecord::Base
end

app/models/adserviceuser.rb
class Adserviceuser < ActiveRecord::Base
end

app/models/beacon.rb
class Beacon < ActiveRecord::Base
end

app/models/beaconlog.rb
class Beaconlog < ActiveRecord::Base
	def hour
	  self.created_at.to_date.strftime('%H')
	end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
end

app/models/dashbutton.rb
class Dashbutton < ActiveRecord::Base
end

app/models/entrance.rb
class Entrance < ActiveRecord::Base
end

app/models/geofencing.rb
class Geofencing < ActiveRecord::Base
end

app/models/iopush.rb
class Iopush < ActiveRecord::Base
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/mastercard.rb
class Mastercard < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/pago.rb
class Pago < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/plastic.rb
class Plastic < ActiveRecord::Base
end

app/models/precio.rb
class Precio < ActiveRecord::Base
end

app/models/preciohora.rb
class Preciohora < ActiveRecord::Base
end

app/models/publicidad.rb
class Publicidad < ActiveRecord::Base
end

app/models/push.rb
class Push < ActiveRecord::Base
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/adserviceusers_controller.rb
class AdserviceusersController < ApplicationController
  before_action :set_adserviceuser, only: [:show, :edit, :update, :destroy]

  # GET /adserviceusers
  # GET /adserviceusers.json
  def index
    @adserviceusers = Adserviceuser.all
  end

  # GET /adserviceusers/1
  # GET /adserviceusers/1.json
  def show
  end

  # GET /adserviceusers/new
  def new
    @adserviceuser = Adserviceuser.new
  end

  # GET /adserviceusers/1/edit
  def edit
  end

  # POST /adserviceusers
  # POST /adserviceusers.json
  def create
    @adserviceuser = Adserviceuser.new(adserviceuser_params)
    @adserviceuser.userid=session[:cuser]
    respond_to do |format|
      if @adserviceuser.save
        format.html { redirect_to @adserviceuser, notice: 'Adserviceuser was successfully created.' }
        format.json { render :show, status: :created, location: @adserviceuser }
      else
        format.html { render :new }
        format.json { render json: @adserviceuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adserviceusers/1
  # PATCH/PUT /adserviceusers/1.json
  def update
    respond_to do |format|
      if @adserviceuser.update(adserviceuser_params)
        format.html { redirect_to @adserviceuser, notice: 'Adserviceuser was successfully updated.' }
        format.json { render :show, status: :ok, location: @adserviceuser }
      else
        format.html { render :edit }
        format.json { render json: @adserviceuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adserviceusers/1
  # DELETE /adserviceusers/1.json
  def destroy
    @adserviceuser.destroy
    respond_to do |format|
      format.html { redirect_to adserviceusers_url, notice: 'Adserviceuser was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adserviceuser
      @adserviceuser = Adserviceuser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adserviceuser_params
      params.require(:adserviceuser).permit(:userid,:beacon)
    end
end

app/helpers/adserviceusers_helper.rb
module AdserviceusersHelper
end

app/views/adserviceusers/_form.html.erb
<%= form_for(@adserviceuser) do |f| %>
  <% if @adserviceuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adserviceuser.errors.count, "error") %> prohibited this adserviceuser from being saved:</h2>

      <ul>
      <% @adserviceuser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %><br>
    <%= f.number_field :userid %>
  </div>

  <div class="field">
    <%= f.label :beacon %><br>
    <%= f.number_field :beacon %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adserviceusers/edit.html.erb
<h1>Editing adserviceuser</h1>

<%= render 'form' %>

<%= link_to 'Show', @adserviceuser %> |
<%= link_to 'Back', adserviceusers_path %>

app/views/adserviceusers/index.html.erb
<h1>Listing adserviceusers</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Beacon minor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adserviceusers.each do |adserviceuser| %>
      <tr>
        <td><%= adserviceuser.userid %></td>
        <td><%= adserviceuser.beacon %></td>
        <td><%= link_to 'Show', adserviceuser %></td>
        <td><%= link_to 'Edit', edit_adserviceuser_path(adserviceuser) %></td>
        <td><%= link_to 'Destroy', adserviceuser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adserviceuser', new_adserviceuser_path %>

app/views/adserviceusers/new.html.erb
<h1>New adserviceuser</h1>

<%= render 'form' %>

<%= link_to 'Back', adserviceusers_path %>

app/views/adserviceusers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @adserviceuser.userid %>
</p>

<%= link_to 'Edit', edit_adserviceuser_path(@adserviceuser) %> |
<%= link_to 'Back', adserviceusers_path %>